MisFit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from users.views import login

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', login, name='home'),
    path('users/', include('users.urls')),
    path('request/', include('employeeRequest.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

employeeRequest/urls.py
from django.conf.urls import url
from .views import *
app_name = 'employeeRequest'
urlpatterns = [
    # url(r'^demo/$', demo, name='demo'),
    url(r'^add_request/$', add_request, name='add_request'),
    url(r'^request_list/$', list_request, name='list_request'),
    url(r'^edit_request/(?P<req_id>[0-9]+)/$', edit_request, name='edit_request'),
    url(r'^edit_request_status/(?P<req_id>[0-9]+)/$', edit_request_status, name='edit_request_status'),
    url(r'^pdf_view/$', pdf_view, name='pdf_view'),
]

users/urls.py
from django.conf.urls import url
from .views import *
app_name = 'users'
urlpatterns = [
    # url(r'^demo/$', demo, name='demo'),

    url(r'^$', login, name='home'),
    url(r'^login/$', login, name='login'),
    url(r'^social_login/$', social_login, name='social_login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^add/$', add_user, name='add_user'),
    url(r'^list/', list_user, name='list_user'),

    url(r'^roles/$', roles_list, name='list_roles'),

    ]

employeeRequest/models.py
from django.db import models
from auditlog.registry import auditlog

# Create your models here.

class EmployeeRequest(models.Model):
    request_name = models.CharField(max_length=50)
    request_details = models.TextField()
    status = models.IntegerField(default=0)
    user = models.ForeignKey('users.User', default=1, on_delete=models.CASCADE)
    created_at = models.DateTimeField(editable=True, null=True)
    modified_at = models.DateTimeField(auto_now=True, null=True)
    created_by = models.ForeignKey('users.User', null=True, blank=True, on_delete=models.CASCADE, related_name='created_by+')
    modified_by = models.ForeignKey('users.User', null=True, blank=True, on_delete=models.CASCADE, related_name='modified_by+')

    def as_json(self):
        return dict(
            request_name=str(self.request_name),
            request_details=str(self.request_details),
            user=self.user_id,
            status = int(self.status),
            created_at = self.created_at,
            modified_at = self.modified_at
        )


auditlog.register(EmployeeRequest)

employeeRequest/forms.py
from django import forms
from .models import *


class AddRequestForm(forms.ModelForm):
    class Meta:
        model = EmployeeRequest
        fields = ('request_name', 'request_details')
        widgets = {

            'request_name': forms.TextInput(attrs={"class": 'form-control', 'required' : 'required','placeholder': 'Request Name'}),
            'request_details': forms.Textarea(attrs={"class": 'form-control', 'required' : 'required','placeholder': 'Request details'}),
        }


class EditRequestForm(forms.ModelForm):
    class Meta:
        model = EmployeeRequest
        fields = ('request_name', 'request_details')
        widgets = {

            'request_name': forms.TextInput(attrs={"class": 'form-control', 'required' : 'required','placeholder': 'Request Name'}),
            'request_details': forms.Textarea(attrs={"class": 'form-control', 'required' : 'required','placeholder': 'Request details'}),
        }


class EditRequestStatusForm(forms.ModelForm):
    CHOICES = (
        ('', '--- Select Status ---',),
        ('0', 'Open',),
        ('1', 'Processed',),
        ('2', 'HR Reviewed',),
    )
    status = forms.ChoiceField(label='Status', widget=forms.Select(attrs={'class': 'form-control'}),
                               choices=CHOICES, required=True)

    class Meta:
        model = EmployeeRequest
        fields = ('status',)

employeeRequest/views.py
from django.shortcuts import render
from MisFit.decorators import *
from .forms import *
from users.models import User



# for pdf purpose . . .
from django.views.generic import View
from django.utils import timezone
from .render_pdf import RenderPdf


@login_required('logged_in', 'users:login')
def list_request(request):
    role_id = request.session['role_id']
    if role_id == 4:
        req = EmployeeRequest.objects.filter(user=request.session['id'])
    else:
        req = EmployeeRequest.objects.all()
    arg = {}
    arg['emp_request'] = "active"
    arg['emp_request_list'] = "active"
    arg['title'] = "Request List"
    arg['req_data'] = req
    arg['redirect_title'] = "Request"
    arg['rediurect_url'] = "employeeRequest:list_request"

    return render(request, 'employeeRequest/request_list.html', arg)


@login_required('logged_in', 'users:login')
def add_request(request):
    arg = {}
    arg['emp_request'] = "active"
    arg['emp_request_list'] = "active"
    arg['btn'] = "Save"
    arg['title'] = "Add Request"
    arg['redirect_title'] = "Request"
    arg['rediurect_url'] = "employeeRequest:list_request"
    arg['form'] = AddRequestForm

    if request.method == 'POST':

        form = AddRequestForm(request.POST, request.FILES)

        if form.is_valid():
            user = User.objects.get(pk=request.session['id'])
            form = form.save(commit=False)
            form.created_at = timezone.now()
            form.modified_at = timezone.now()
            form.created_by = user
            form.modified_by = user
            form.user = user
            form.save()
            messages.success(request, 'Request Added')
            return redirect('employeeRequest:list_request')

        else:
            arg['form'] = form
            return render(request, 'includes/common_form.html', arg)

    return render(request, 'includes/common_form.html', arg)



@login_required('logged_in', 'users:login')
def edit_request(request, req_id):
    try:
        emp_request = EmployeeRequest.objects.get(id=req_id)
        # Set permission for employee not to allow edit when status is in processing
        if emp_request.status != 0 and request.session['role_id'] == 4:
            messages.error(request, 'You are not allowed anymore to update your request anymore when request is in processing.')
            return redirect('employeeRequest:list_request')
    except EmployeeRequest.DoesNotExist:
        return render(request, '404.html')

    arg = {}
    arg['emp_request'] = "active"
    arg['emp_request_list'] = "active"
    arg['btn'] = "Update"
    arg['title'] = "Update Request"
    arg['redirect_title'] = "Request"
    arg['rediurect_url'] = "employeeRequest:list_request"
    arg['form'] = EditRequestForm(instance=emp_request)

    if request.method == 'POST':

        form = EditRequestForm(request.POST, instance=emp_request)

        if form.is_valid():
            user = User.objects.get(pk=request.session['id'])
            form_data = form.save(commit=False)
            form_data.modified_by = user
            form_data.save()
            messages.success(request, 'Request Updated')
            return redirect('employeeRequest:list_request')
        else:
            arg['form'] = form
            return render(request, 'includes/common_form.html', arg)

    return render(request, 'includes/common_form.html', arg)


@login_required('logged_in', 'users:login')
def edit_request_status(request, req_id):
    try:
        emp_request = EmployeeRequest.objects.get(id=req_id)
        # Set permission for employee not to allow status update
        if request.session['role_id'] == 4:
            messages.error(request, 'Only HR and Manager are allowed to update your status.')
            return redirect('employeeRequest:list_request')
        else:
            pass
    except EmployeeRequest.DoesNotExist:
        return render(request, '404.html')

    arg = {}
    arg['emp_request'] = "active"
    arg['emp_request_list'] = "active"
    arg['btn'] = "Update"
    arg['title'] = "Update Status"
    arg['redirect_title'] = "Request"
    arg['rediurect_url'] = "employeeRequest:list_request"
    arg['form'] = EditRequestStatusForm(instance=emp_request)

    if request.method == 'POST':

        form = EditRequestStatusForm(request.POST, instance=emp_request)

        if form.is_valid():
            user = User.objects.get(pk=request.session['id'])
            form_data = form.save(commit=False)
            form_data.modified_by = user
            form_data.save()
            messages.success(request, 'Request Status Updated')
            return redirect('employeeRequest:list_request')
        else:
            arg['form'] = form
            return render(request, 'includes/common_form.html', arg)

    return render(request, 'includes/common_form.html', arg)



def pdf_view(request):
    role_id = request.session['role_id']
    if role_id != 4:
        requested_data = EmployeeRequest.objects.all()
    else:
        messages.error(request, 'Sorry, Only HR and Manager are allowed to download.')
        return redirect('employeeRequest:list_request')

    today = timezone.now()
    arg = {
        'today': today,
        'requested_data': requested_data
    }
    return RenderPdf.render('employeeRequest/pdf.html', arg)

employeeRequest/templates/employeeRequest/pdf.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Employee Request Report</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }
        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }
        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }
        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }
        .table tbody + tbody {
            border-top: 2px solid #000;
        }
        .table .table {
            background-color: #fff;
        }
        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }
        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }
    </style>
</head>
<body>

<div class="container">
    <div class="card">
        <div class="card-header">
            <h3>Employee Request List - {{ today | date:"d/m/Y" }}</h3>
        </div>

        <table class="table">
            <thead>
            <tr>
                <th>Request Name</th>
                <th>Request Details</th>
                <th>Status</th>
                <th>Requested By</th>
                <th>Requested Time</th>
                <th> Last Modified By </th>
            </tr>
            </thead>
            <tbody>
            {% for requestedData in requested_data %}
                <tr>
                    <td>{{ requestedData.request_name }}</td>
                    <td>{{ requestedData.request_details }}</td>
                    <td>
                        {% if requestedData.status == 0 %}
                            Open
                        {% elif requestedData.status == 1 %}
                            Processed
                        {% elif requestedData.status == 2 %}
                            HR Reviewed
                        {% elif requestedData.status == 3 %}
                            Done
                        {% endif %}
                    </td>
                    <td>{{ requestedData.user.first_name | title }} {{ requestedData.user.last_name | title }}</td>
                    <td>{{ requestedData.created_at | date:"Y-m-d H:i:s" }}</td>
                    <td>
                        {{ requestedData.modified_by.first_name | title }} {{ requestedData.modified_by.last_name | title }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

</body>
</html>

employeeRequest/templates/employeeRequest/request_list.html
{% extends 'base.html' %}
{% load static %}
{% load imagekit %}


{% block content %}

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-dark">
                        <i class="icon-list font-dark"></i>
                        <span class="caption-subject bold uppercase">{{title}}</span>
                    </div>

                </div>
                 {% include 'includes/message_template.html' %}
                <div class="portlet-body">
                    <div class="table-toolbar">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="btn-group">
                                     <a href="{% url 'employeeRequest:add_request' %}" id="sample_editable_1_new" class="btn sbold green">Add New
                                        <i class="fa fa-plus"></i></a>
                                </div>
                                <div class="btn-group">
                                     <a target="_blank" href="{% url 'employeeRequest:pdf_view' %}" id="sample_editable_1_new" class="btn sbold green">Download
                                        <i class="fa fa-download"></i></a>
                                </div>
                            </div>

                        </div>
                    </div>

                    <table id="sample_1" class="table table-striped table-bordered table-hover table-checkable order-column">
                            <thead>
                            <tr>
                                <th class="display-none"></th>
                                <th> Request Name </th>
                                <th> Request Details </th>
                                <th> Requested By </th>
                                <th> Requested Time </th>
                                <th> Last Modified By </th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for request in req_data %}
                                <tr class="odd gradeX">

                                    <td class="display-none"></td>
                                    <td>{{ request.request_name }}</td>
                                    <td>{{ request.request_details }}</td>
                                    <td>
                                        {{ request.user.first_name | title }} {{ request.user.last_name | title }}
                                    </td>
                                    <td>{{ request.created_at | date:"Y-m-d H:i:s" }}</td>
                                    <td>
                                        {{ request.modified_by.first_name | title }} {{ request.modified_by.last_name | title }}
                                    </td>
                                    <td>
                                         {% if request.status == 0 %}
                                            <span class="label label-sm label-success"> Open </span>
                                         {% elif request.status == 1 %}
                                            <span class="label label-sm label-success"> Processed </span>
                                         {% elif request.status == 2 %}
                                            <span class="label label-sm label-success"> HR Reviewed </span>
                                         {% elif request.status == 3 %}
                                            <span class="label label-sm label-success"> Done </span>
                                         {% endif %}
                                    </td>
                                    <td>
                                        <a href="{% url 'employeeRequest:edit_request' request.id %}" class="btn btn-sm btn-primary">Edit</a>
                                        <a href="{% url 'employeeRequest:edit_request_status' request.id %}" class="btn btn-sm btn-primary">Change Status</a>
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>

                        </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>

{% endblock %}