MisFit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from users.views import login

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', login, name='home'),
    path('users/', include('users.urls')),
    path('request/', include('employeeRequest.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

users/urls.py
from django.conf.urls import url
from .views import *
app_name = 'users'
urlpatterns = [
    # url(r'^demo/$', demo, name='demo'),

    url(r'^$', login, name='home'),
    url(r'^login/$', login, name='login'),
    url(r'^social_login/$', social_login, name='social_login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^add/$', add_user, name='add_user'),
    url(r'^list/', list_user, name='list_user'),

    url(r'^roles/$', roles_list, name='list_roles'),

    ]

templates/401.html
{% extends 'base.html' %}
{% load static %}
{% load imagekit %}
{% block content %}
<!--this section for bradcramb (page-bar section included from base.html)-->
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12 page-404">
                    <div class="number font-green"> 401 </div>
                    <div class="details">
                        <h2>Oops! You're lost!</h2>
                        <h3 class="text-danger"> Access Denied.</h3>
                        <p>Sorry, you have no right access to enter this page.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
{% include 'includes/header.html' %}

{% block additional_css %}

{% endblock %}
</head>
 <body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white">
        <p class="loading_loader" id="loading_loader"><img src="/assets/ajax-loader.gif"></p>
        <div class="page-wrapper">
            <!-- BEGIN HEADER -->
            <div class="page-header navbar navbar-fixed-top">
                <!-- BEGIN HEADER INNER -->
                <div class="page-header-inner ">
                    <!-- BEGIN LOGO -->
                    <div class="page-logo">
                        <a href="{% url 'users:list_user' %}">
                            <h4>MisFit HR</h4>
                        </a>
                        <div class="menu-toggler sidebar-toggler">
                            <span></span>
                        </div>
                    </div>
                    <!-- END LOGO -->
                    <!-- BEGIN RESPONSIVE MENU TOGGLER -->
                    <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
                        <span></span>
                    </a>
                    <!-- END RESPONSIVE MENU TOGGLER -->
                    <!-- BEGIN TOP NAVIGATION MENU -->
                    <div class="top-menu custom_notification">
                        <ul class="nav navbar-nav pull-right">
                            <!-- BEGIN USER LOGIN DROPDOWN -->
                            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                            <li class="dropdown dropdown-user">
                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                    <img alt="" class="img-circle" src="{% static '' %}{{ request.session.photo }}" />
                                    <span class="username username-hide-on-mobile"> {{ request.session.email }} </span>
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-default">
                                    <li>
                                        <a href="{% url 'users:logout' %}">
                                            <i class="icon-key"></i> Log Out </a>
                                    </li>
                                </ul>
                            </li>
                            <!-- END USER LOGIN DROPDOWN -->
                            <!-- BEGIN QUICK SIDEBAR TOGGLER -->
                            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                            <li class="dropdown dropdown-quick-sidebar-toggler">
                                <a href="{% url 'users:logout' %}" class="dropdown-toggle">
                                    <i class="icon-logout"></i>
                                </a>
                            </li>
                            <!-- END QUICK SIDEBAR TOGGLER -->
                        </ul>
                    </div>
                    <!-- END TOP NAVIGATION MENU -->
                </div>
                <!-- END HEADER INNER -->
            </div>
            <div class="clearfix"> </div>
            <div class="page-container">
                {% include 'includes/left-nav-menu-dev.html' %}

                <!-- BEGIN CONTENT -->
                <div class="page-content-wrapper">
                    <!-- BEGIN CONTENT BODY -->
                    <div class="page-content">
                        <!-- BEGIN PAGE HEADER-->
                        <div class="page-bar">
                            <ul class="page-breadcrumb">
{#                                {% if not no_sub_breadcrumb %}#}
{#                                <li>#}
{#                                    <a href="{% url 'users:list_user' %}">Dashboard</a>#}
{#                                    <i class="fa fa-angle-right "></i>#}
{#                                </li>#}
{#                                {% endif %}#}
                                {% if rediurect_url %}
                                    <li>
                                        <a href="{% url rediurect_url %}">{{ redirect_title }}</a>
                                         <i class="fa fa-angle-right " aria-hidden="true"></i>
                                    </li>
                                {% endif %}
                                <li>
                                    <span>{{title}}</span>
                                </li>
                            </ul>


                        </div>
                        <!-- BEGIN THEME PANEL -->
                            {% block content %}

                            {% endblock %}

                    </div>
                    <!-- END CONTENT BODY -->
                </div>
                <!-- END CONTENT -->
                    </div>
                </div>
                {% include 'includes/footer.html' %}
                {% block additional_script %}

                {% endblock %}
            </body>

</html>

templates/base_login.html
{% load static %}
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->
    <head>
        <meta charset="utf-8" />
        <title>{{ browser_title }} | MisFit HR</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="Preview page of Metronic Admin Theme #1 for " name="description" />
        <meta content="" name="author" />
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        <link href="{% static '' %}global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="{% static '' %}global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
        <link href="{% static '' %}global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

        <!-- END GLOBAL MANDATORY STYLES -->\
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="{% static '' %}global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
        <link href="{% static '' %}global/css/plugins.min.css" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        <!-- BEGIN PAGE LEVEL STYLES -->
        <link href="{% static '' %}pages/css/login-4.min.css" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <!-- END THEME LAYOUT STYLES -->
		<link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
        <link href="{% static '' %}global/css/custom.css" rel="stylesheet" type="text/css" />
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}" /> </head>
    <!-- END HEAD -->

    <body class=" login">
        <!-- BEGIN LOGO -->
        <div class="logo">
            <span class="copyright">MisFit HR Control Panel </span>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN LOGIN -->
        <div class="content">

                    {% block content %}

                    {% endblock %}


        </div>
        <!-- END LOGIN -->
        <!-- BEGIN COPYRIGHT -->
        <div class="copyright"> 2019 &copy; MisFit HR Control Panel </div>
        <!-- END COPYRIGHT -->
        <!--[if lt IE 9]>
<script src="{% static '' %}global/plugins/respond.min.js"></script>
<script src="{% static '' %}global/plugins/excanvas.min.js"></script>
<script src="{% static '' %}global/plugins/ie8.fix.min.js"></script>
<![endif]-->
        <!-- BEGIN CORE PLUGINS -->
        <script src="{% static '' %}global/plugins/jquery.min.js" type="text/javascript"></script>
        <script src="{% static '' %}global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="{% static '' %}global/plugins/js.cookie.min.js" type="text/javascript"></script>
        <script src="{% static '' %}global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="{% static '' %}global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="{% static '' %}global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="{% static '' %}global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
        <script src="{% static '' %}global/plugins/jquery-validation/js/additional-methods.min.js" type="text/javascript"></script>
        <script src="{% static '' %}global/plugins/select2/js/select2.full.min.js" type="text/javascript"></script>
        <script src="{% static '' %}global/plugins/backstretch/jquery.backstretch.min.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="{% static '' %}global/scripts/app.min.js" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="{% static '' %}pages/scripts/login-4.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <!-- END THEME LAYOUT SCRIPTS -->
    </body>

</html>